name: Azure
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
        - 'azure/**'
  pull_request:
    branches: [ "main" ]
    paths:
        - 'azure/**'

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10' 
      - name: Install dependencies
        run: |
          pip install -r azure/python/requirements.txt
      - name: run script
        run: python azure/python/main.py

  bender:
    runs-on: ubuntu-latest
    needs: [python]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Debug job with bender (if failure)
        uses: ahelal/bender-action@main
        with:
          gh-token: ${{ secrets.GHTOKEN }}
          az-openai-endpoint: ${{vars.AZOPENAIENDPOINT}}
          az-openai-deployment: ${{secrets.AZOPENAIDEPLOYMENT}}
          az-openai-key: ${{secrets.AZOPENAIKEY}}
          # az-openai-apiVersion:
          # job-context:
          # user-context: