name: Azure CLI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
    - name: 'Az CLI command'
      run: az group list
    - name: 'Az CLI command'
      run: az group create --name myResourceGroup --location eastus

  bender:
    runs-on: ubuntu-latest
    needs: [cli]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get dir context
        id: getdir
        run: |
          echo "dir_context=$(find . -path ./.git -prune -o -print | tr '\n' ' ' | base64)" >> $GITHUB_ENV
          
      - name: Echo dir context
        run: echo "\'${{env.dir_context}}\'"


      - name: Run Bender (if failure)
        uses: ahelal/bender-action@fixes
        with:
          gh-token: ${{ secrets.GHTOKEN }}
          az-openai-endpoint: ${{vars.AZOPENAIENDPOINT}}
          az-openai-deployment: ${{secrets.AZOPENAIDEPLOYMENT}}
          az-openai-key: ${{secrets.AZOPENAIKEY}}
          dir-context: ${{ env.dir_context }}
          # az-openai-apiVersion:
          # job-context:
          # user-context: