name: Azure Bicep
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  bicep:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          auth-type: "SERVICE_PRINCIPAL"

    - name: 'Deploy bicep'
      run: ./azure/bicep-name-conflict/deploy.sh
  bicep2:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
    
        - name: 'Az CLI login'
          uses: azure/login@v1
          with:
              creds: '${{ secrets.AZURE_CREDENTIALS }}'
              auth-type: "SERVICE_PRINCIPAL"
    
        - name: 'Deploy bicep'
          run: ./azure/bicep-name-conflict/deploy.sh
    

  bender:
    runs-on: ubuntu-latest
    needs: [bicep, bicep2]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get dir context
        id: getdir
        run: echo "dir_context=$(find . -path ./.git -prune -o -print | base64 | tr '\n' ' ')" >> $GITHUB_ENV
          
      - name: Echo dir context
        run: echo "\'${{env.dir_context}}\'"

      - name: Run Bender (if failure)
        uses: ahelal/bender-action@${{vars.BENDER_VERSION}}
        with:
          gh-token: ${{ secrets.GHTOKEN }}
          az-openai-endpoint: ${{vars.AZOPENAIENDPOINT}}
          az-openai-deployment: ${{secrets.AZOPENAIDEPLOYMENT}}
          az-openai-key: ${{secrets.AZOPENAIKEY}}
          dir-context: ${{ env.dir_context }}
