# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  jobA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Create A
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "1" > a.text
      - name: Run ls 
        run: ls -la 
      - name: Fail
        run: |
          echo "2" > a-fail.text
          exit 1
      - name: Run if Create A fails
        if: failure()
        run: echo "The Create A step failed."
     # run this step if any of the above fails

  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Create b
        run: |
          echo "1" > b.text
      - name: Run ls 
        run: ls -la
