# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: 'World'
        type: string


jobs:
  jobA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Create A
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "1" > a.text
      - name: Run ls 
        run: ls -la
      - name: Fail
        run: |
          echo "2" > a-fail.text
          exit 1
  jobB:
    runs-on: ubuntu-latest
    needs: jobA
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Create b
        run: |
          echo "1" > b.text
      - name: Run ls 
        run: ls -la
  bender:
    runs-on: ubuntu-latest
    needs: [jobA, jobB]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Debug job with bender (if failure)
        uses: ahelal/bender-action@main
        with:
          gh-token: ${{ secrets.GHTOKEN }}
          az-openai-endpoint: ${{vars.AZOPENAIENDPOINT}}
          az-openai-deployment: ${{secrets.AZOPENAIDEPLOYMENT}}
          az-openai-key: ${{secrets.AZOPENAIKEY}}
          # az-openai-apiVersion:
          # job-context:
          # user-context: